#!/usr/bin/env bash
# install nginx on my web serve web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
