#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
	listen 80 default_server;

	root /var/www/html;
	index index.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > default_file
sudo mv -f default_file /etc/nginx/sites-enabled/default
sudo service nginx restart

