#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string# Ceci n'est pas une page and also return an http 404 error code
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
        listen 80 default_server;
	add_header X-Served-By $(hostname);
        root /var/www/html;
        index index.html;

	error_page 404 /404.html;
	location = /404.html{
		internal;
	}

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > default_file
sudo mv -f default_file /etc/nginx/sites-enabled/default
sudo service nginx restart
