#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

SETUP="frontend myapp
        bind *:80
        default_backend myapp_servers
backend myapp_servers
        balance roundrobin
        server server1 54.173.2.233
        server server2 54.210.243.50
"
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "$SETUP" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart

