#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

SETUP="frontend olu-age-tech-frontend
        bind *:80
        default_backend olu-age-tech-backend
backend olu-age-tech-backend
        balance roundrobin
        server 137831-web-01 54.159.24.15:80 check
        server 137831-web-02 54.209.116.192:80 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg backup2
echo "$SETUP" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart

