#!/usr/bin/env bash
# changes listening port to 80
# first delete the existing sites-enabled then replace it with sites-available
rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

