#!/usr/bin/env bash
#script that displays numbers from 1 to 100
#Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number in a list format


j=3
k=5
l=15
for i in {1..100}; do
    if [[ $((i%l)) -eq 0 ]]; then
        echo "FizzBuzz"
    elif [[ $((i%j)) -eq 0 ]]; then
            echo "Fizz"
    elif [[ $((i%k)) -eq 0 ]]; then
            echo "Buzz"
    else
        echo "$i"
    fi
done