#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd
# script will only display:
# username
# user id
# Home directory path for the user

file="/etc/passwd"
while read -r line; do
echo "$line"
done < "$file"
