#!/usr/bin/env bash
#script that displays the visitor IP along with the HTTP status code from the Apache log file

file="apache-access.log"
awk '{ for (i=1; i<=NF; i++) if ($i ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/) print $i }' $file
