#!/usr/bin/env bash
#script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
var='Best School'
i=0

while [ $i -lt 10 ]; do
    if [[ $i == 8 ]]; then
        echo "Hi"
    else
        echo "$var"
    fi
((i++))
done