#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

#cp host file to a new file
cp /etc/hosts ~/hosts.new
#remove line that comtain 127.0.0.1 from the file
sed -i $'s/127.0.0.1\s*localhost//g'  ~/hosts.new

#add new line to the hosts.new file
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8      facebook.com" >> ~/hosts.new

#copy the hosts.new file to old the original hosts file
cp -f ~/hosts.new /etc/hosts

#remove the hosts.new
#rm ~/hosts.new