#!/usr/bin/env bash
# a web server runing on Nginx as the nginx user listening on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replacing port 80 with port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# onwer permission read and write only
chmod 644 /etc/nginx/nginx.conf 
# to stop nginx in other to kill itif is runnig
pkill apache2

sudo -u nginx service nginx start
