#!/usr/bin/env bash

# Get the process IDs of the running Gunicorn instances
pidList="$(pgrep gunicorn)"

# Send a HUP signal to each Gunicorn process
for pid in $pidList; do
	echo "Reloading Gunicorn process $pid"
	kill -HUP "$pid"
done

