#!/usr/bin/env bash
# A bash script that creates an RSA key pair
# name of the created private key must be school
# number of bits in the created key to be created 4096
# the created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -p betty -f school
